---
title: "An Example Literate Data Contract"
format: html
---

```{r setup, include=FALSE}
library(pointblank)
```

# Penguins Table Contract

## 

```{r create_agent, echo=TRUE}
agent <-
  create_agent(
    tbl = ~ palmerpenguins::penguins,
    actions = action_levels(
      warn_at = 0.05,
      stop_at = 0.10
    ),
    tbl_name = "palmerpenguins::penguins",
    label = "Validation plan generated by `draft_validation()`."
  ) 
```

```{r} 
agent <- agent %>%
  # Expect that column `species` is of type: factor
  col_is_factor(
    columns = c("species")
  )
```

```{r} 
agent <- agent %>%
  # Expect that column `island` is of type: factor
  col_is_factor(
    columns = c("island")
  ) 
```

```{r} 
agent <- agent %>%
  # Expect that column `bill_length_mm` is of type: numeric
  col_is_numeric(
    columns = c("bill_length_mm")
  ) %>%
  # Expect that values in `bill_length_mm` should be between `32.1` and `59.6`
  col_vals_between(
    columns = c("bill_length_mm"),
    left = 32.1,
    right = 59.6,
    na_pass = TRUE
  ) 
```
```{r}
agent <- agent %>%
  # Expect that column `bill_depth_mm` is of type: numeric
  col_is_numeric(
    columns = c("bill_depth_mm")
  ) %>%
  # Expect that values in `bill_depth_mm` should be between `13.1` and `21.5`
  col_vals_between(
    columns = c("bill_depth_mm"),
    left = 13.1,
    right = 21.5,
    na_pass = TRUE
  ) 
```
```{r}
agent <- agent %>%
  # Expect that column `flipper_length_mm` is of type: integer
  col_is_integer(
    columns = c("flipper_length_mm")
  ) %>%
  # Expect that values in `flipper_length_mm` should be between `172` and `231`
  col_vals_between(
    columns = c("flipper_length_mm"),
    left = 172,
    right = 231,
    na_pass = TRUE
  ) 
```
```{r}
agent <- agent %>%
  # Expect that column `body_mass_g` is of type: integer
  col_is_integer(
    columns = c("body_mass_g")
  ) %>%
  # Expect that column `sex` is of type: factor
  col_is_factor(
    columns = c("sex")
  ) %>%
  # Expect that column `year` is of type: integer
  col_is_integer(
    columns = c("year")
  ) %>%
  # Expect entirely distinct rows across `species, island, bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g, sex, year`
  rows_distinct(
    columns = c("species, island, bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g, sex, year")
  ) %>%
  # Expect that column schemas match
  col_schema_match(
    schema = col_schema(
      species = "factor",
      island = "factor",
      bill_length_mm = "numeric",
      bill_depth_mm = "numeric",
      flipper_length_mm = "integer",
      body_mass_g = "integer",
      sex = "factor",
      year = "integer"
    )
  ) %>%
  interrogate()
```


```{r print_agent, echo=FALSE}
agent
```

